### ISSUE TITLE
INTERNAL - unable to enqueue for inference

### ISSUE THREAD

**Issue by marcozhguo** [NVIDIA/tensorrt-inference-server#29]
Hello, I have run my tensorrt model on tensorrt inference server, but when I invoke ctx->Run(&(results->back())) or ctx.GetAsyncRunResults(&(results->back()), request, true) to get model infer results，error occur:**INTERNAL - unable to enqueue for inference rec_white_nbi_0_0_gpu0.**
**According to localhost:8000/api/status , model status is ready, as shown below.**
![image](https://user-images.githubusercontent.com/28585308/50510204-c914e100-0ac3-11e9-8376-8a6a2216e60d.png)
**Model Definition Files config.pbtxt  as shown follow.**
![image](https://user-images.githubusercontent.com/28585308/50510500-e6967a80-0ac4-11e9-9cc8-b8eae779796e.png)
**nvidia inference server log**
![image](https://user-images.githubusercontent.com/28585308/50534753-5fa4d900-0b7c-11e9-9323-778aa1517325.png)
I have looked inside cudnn.h for a description of the error codes, Cudnn Error in execute: 3 refers to bad param, Does it mean there exists some wrong params setting in my TRTIS client program？
**my tensorrt inference client progream**
![image](https://user-images.githubusercontent.com/28585308/50511320-33c81b80-0ac8-11e9-8f20-30d29eebf100.png)
![image](https://user-images.githubusercontent.com/28585308/50511323-3591df00-0ac8-11e9-9676-dc456577250c.png)
![image](https://user-images.githubusercontent.com/28585308/50511329-37f43900-0ac8-11e9-956b-7b3aef22d0f9.png)
I know the error is related to nvinfer1::IExecutionContext，but I don't know the cause of the error, if anyone know the cause, please help me, thank you!

**Comment by deadeyegoodwin** [comment]
It looks like you are using the latest version of TRTIS (0.9.0). Since you are using a TensorRT model you must make sure that the model was built with the same version of TensorRT as is used by TRTIS. For 0.9.0 that means TensorRT 5.0.2 as is noted in the Release Notes (https://docs.nvidia.com/deeplearning/sdk/inference-release-notes/rel_18.12.html#rel_18.12).

Can you confirm that you built your TensorRT plan using TensorRT version 5.0.2.

**Comment by marcozhguo** [comment]
I use TensorRT 5.0.2 to rebuild TensorRT plan and the problem is solved.  Thank for help.  The problem is due to the TensorRT plan is built on TensorRT 5.0.0, while TRTIS 18.12 is compatible with TensorRT 5.0.2. I have a suggestion that TRTIS  can output more detailed logs , which is easier for developers to troubleshoot.

**Comment by marcozhguo** [comment]
In addition, if TensorRT plan version is not compatible with TRTIS, the state of model should not be ready, which will cause confusion.

**Comment by deadeyegoodwin** [comment]
This is a known issue with the TensorRT runtime. TRTIS has no way to determine the version of the plan file and so must rely on TRT runtime to report an accurate error. As you have seen there are cases where this does not happen. TRT runtime is expected to improve in this area going forward. Thanks for reporting this issue.
